#!/bin/sh -e
if [ -f "/data/ports" ]; then
    echo "Found /data/ports, start service: frp_allowed_ports"
    exec /usr/local/bin/frp_allowed_ports -l 127.0.0.1:9002  -p /data/ports 2>&1
else
    echo "Not Found /data/ports, won't start service: frp_allowed_ports"
    sv stop frp_allowed_ports
fi
